#!/bin/bash

allpassed=0
passed=0
skipped=0
failed=0

echo
echo "Running tests..."
echo

for t in $(echo $@ | tr ' ' '\n' | sort) ; do
    if [ ! -x $t ] ; then
        allpassed=1
        skipped=$(( $skipped + 1 ))
        echo "$t...    SKIPPED - executable missing, compilation failure?"
        continue
    fi
    outfile=$(mktemp out.XXXXXX)
    ./$t >$outfile 2>&1
    retcode=$?
    if [ $retcode -eq 0 ] ; then
        passed=$(( $passed + 1 ))
        echo "$t...    passed"
    else
        allpassed=1
        failed=$(( $failed + 1 ))
        echo "$t...    FAILED"
        echo "Output of failed test follows"
        cat $outfile
    fi
    rm -f $outfile
done

if [ $allpassed -eq 0 ] ; then
    echo
    echo "$passed tests passed"
    exit 0
else
    echo
    echo "$passed tests passed"
    echo "$failed TESTS FAILED"
    echo "$skipped TESTS SKIPPED"
    exit 1
fi
